name: package-manager-publish-r
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        R: [ '3.5.3', '3.6.1','4.2.3','4.3.1' ]
    name: R ${{ matrix.R }} Test packages
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 2
        extra-packages: |
          any::ggplot2
          any::rcmdcheck
        needs: |
          website
          coverage
